project:
  type: default
  output-dir: docs
  render:
    - index.qmd
    - schedule.qmd
    - syllabus.qmd
    - notes/day*.qmd
    - quizzes/*.qmd

format:
  html:
    theme: cosmo
  pdf:
    toc: false
