---
format: beamer
title: 1.3 Matrix Equations
author: Jeremy Teitelbaum
jupyter:
    kernelspec:
        name: "base"
        language: "python"
        display_name: "base"
---

## Vectors

A vector (in $\mathbf{R}^{n}$) is an $n$-tuple of real numbers.  For example

$$
v = (-1,3,2,5,0,7)
$$

is a vector in $\mathbf{R}^{6}$.

Vectors can be written as matrices with one column (column vectors).

$$
v = \begin{pmatrix} -1 \\ 3\\2\\5\\0\\7\end{pmatrix}
$$

## Vector arithmetic

Vectors can be added:

$$
\begin{pmatrix} 1 \\ -3\\ 5\end{pmatrix} + \begin{pmatrix} 4 \\ -1 \\11\end{pmatrix} = \begin{pmatrix} 5 \\-4\\16\end{pmatrix}
$$

Vectors can be multiplied by a number (a *scalar*):

$$
\begin{pmatrix} 1 \\ -3 \\5\end{pmatrix} = \begin{pmatrix} 3 \\ -9 \\ 15\end{pmatrix}
$$


## Geometry: Scalar Multiplication

If $\mathbf{v}$ is a vector, and $a$ is a scalar (a real number) then $av$ "points in the same direction" but it's length is "scaled by $a$."


```{python}
import matplotlib.pyplot as plt

x_start, y_start = 0,0
x_comp,y_comp = 2,3
plt.figure()
plt.quiver(0,0,2,3,color="g",angles="xy",scale=1,scale_units="xy")
plt.quiver(0,0,4,6,color="r",scale=1,angles="xy",scale_units="xy",alpha=.5)
plt.quiver(0,0,-2,-3,scale=1,color="black",angles="xy",scale_units="xy",alpha=.5)
plt.xlim(-7,7)
plt.ylim(-7,7)
plt.title("Scalar multiplication")
plt.xlabel("X axis")
plt.ylabel("Y axis")
plt.text(2.3,2.7,"v",fontsize=16)
plt.text(4.3,6,"2v",fontsize=16)
plt.text(-2.3,-2.7,"-v",fontsize=16)
plt.grid()
plt.show()
```


## Geometry: Addition

```{python}
import matplotlib.pyplot as plt

# Starting point of the vector
x_start, y_start = 0, 0

# Components of the vector (2,3)
x_comp, y_comp = 2, 3

# Create the plot
plt.figure()
plt.quiver(
    x_start, y_start, x_comp, y_comp, angles="xy", scale_units="xy", scale=1, color="r"
)
plt.quiver(0, 0, -1, 2, angles="xy", scale_units="xy", scale=1, color="g")

plt.quiver(-1, 2, 2, 3, angles="xy", scale_units="xy", scale=1, color="r")

plt.quiver(2, 3, -1, 2, angles="xy", scale_units="xy", scale=1)

plt.quiver(0, 0, 1, 5, angles="xy", scale_units="xy", scale=1)

plt.text(-1, 1, "(-1,2)", fontsize=12)
plt.text(1, 1, "(2,3)", fontsize=12)
plt.text(1.2, 5.2, "sum of (-1,2) and (2,3)", fontsize=12)
# Optionally, set the plot limits
plt.xlim(-3, 3)
plt.ylim(0, 6)

# Optionally, add grid, labels, and title
plt.grid(True)
plt.xlabel("X axis")
plt.ylabel("Y axis")


# Display the plot
plt.show()
```

This illustrates the "parallelogram law." A similar picture holds in higher dimensions but is hard to draw.

## Linear combinations

If $v_1,v_2,\ldots, v_k$ are $k$ vectors in $\mathbf{R}^{n}$,
and $a_1,\ldots, a_k$ are constants (scalars),
then the vector
$$
y = a_1v_1+a_2v_2+\cdots +a_k v_k
$$
is called a *linear combination* of $v_1,\ldots, v_k$. 

## Linear Combination Example

If 
$$
\begin{matrix}
v_1 = \begin{pmatrix} 1 \\ 1 \\ 0 \end{pmatrix}
&
v_2 = \begin{pmatrix} 0 \\ 1 \\ 1 \end{pmatrix}
\end{matrix}$$

then the linear combinations of $v_1$ and $v_2$ are
$$
y = a_1 v_1 + a_2 v_2 = \begin{pmatrix} a_1 \\ a_1 \\  0\end{pmatrix} + \begin{pmatrix} 0 \\ a_2 \\ a_2 \end{pmatrix} = \begin{pmatrix} a_1 \\ a_1+a_2 \\ a_2\end{pmatrix}
$$

## Span

The *span* of a set of vectors in $\mathbf{R}^{n}$ is the collection of all possible linear combinations of the set. 

In the previous example, the span of $v_1$ and $v_2$ is all vectors $\begin{pmatrix} x \\ y \\ z\end{pmatrix}$ such that you can find $a_1$ and $a_2$ so that:

$$
\begin{pmatrix} x \\ y \\ z\end{pmatrix}=\begin{pmatrix} a_1 \\ a_1 \\ 0\end{pmatrix} + \begin{pmatrix} 0 \\ a_2 \\ a_2\end{pmatrix}
$$

## Span (continued)

This means that $\begin{pmatrix} x \\ y \\ z\end{pmatrix}$ is in the span of $v_1$ and $v_2$ if, **given** $x,y,z$, you can **find** $a_1,a_2$ so that
$$
\begin{matrix}
a_1 &=& x \\
a_1+a_2 &=& y \\
a_2 &=& z\\
\end{matrix}
$$

## Span (continued)

In augmented matrix form this is

$$
\begin{pmatrix}
1 & 0 & x \\
1 & 1 & y \\
0 & 1 & z \\
\end{pmatrix}
$$

## Span (continued)

Using row reduction this yields

$$
\begin{pmatrix}
1 & 0 & x \\
0 & 1 & y-x \\
0 & 0 & z-y+x \\
\end{pmatrix}
$$

This system has a solution (is consistent) exactly when $z-y+x=0$ or $y=z+x$.

## Span (continued)

So
$$
v = \begin{pmatrix} 2 \\ 1 \\ -1\end{pmatrix}
$$
is in the span, but
$$
w = \begin{pmatrix} 2 \\ 1 \\ 1\end{pmatrix}
$$
is not.

## Span (continued)

More generally if $v_1, \ldots, v_k$ are vectors in $\mathbf{R}^{n}$, then a vector $w$ in $\mathbf{R}^{n}$ belongs to the span of the $v_{i}$ if and only if the linear system with augmented matrix

$$
M = \left[\begin{matrix} v_1 & v_2 & \cdots & v_k & w\end{matrix}\right]
$$

has a solution (is consistent).  

Here the matrix $M$ has the indicated vectors as its columns.  It is an $n\times (k+1)$ matrix. 


## Examples

Is $$\begin{pmatrix} -5\\11\\-7\end{pmatrix}$$
in the span of the vectors
$$
\begin{pmatrix}1 \\ -2 \\2\end{pmatrix},\begin{pmatrix} 0 \\5\\5\end{pmatrix},\begin{pmatrix}2\\0\\8\end{pmatrix}
$$

## Matrix form

Associated matrix

```{python}
from sympy import Matrix,init_printing
init_printing()
M = Matrix([[1,0,2,-5],[-2,5,0,11],[2,5,8,-7]])
M
```

Echelon Form:
```{python}
M.rref()[0]
```

So the last column is *not* in the span of the first three.

